### PR TITLE
[AMORO-2696] Upgrade Optimizer Spark Docker File

### LINKED ISSUE #2696: [Improvement]: Upgrade Optimizer Spark Docker File
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

aws version jar upgrade to 2.24.12

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by tcodehuber**
## Why are the changes needed?

Close #2696.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by baiyangtx** [comment]
Why did we need to upgrade our AWS version to 2.24.12 and did we run into any issues?

**Review by baiyangtx — COMMENTED** [review]
Why did we need to upgrade our AWS version to 2.24.12 and did we run into any issues?

**Comment by tcodehuber** [comment]
> Why did we need to upgrade our AWS version to 2.24.12 and did we run into any issues?

We can keep up with https://github.com/apache/incubator-amoro/pull/2682

**Comment by zhoujinsong** [comment]
@baiyangtx  FYI, We bumped up the aws dependencies' version to 2.24.12 in #2583.

**Review by zhoujinsong — APPROVED** [review]
LGTM.

**Pull request merged**
