### PR TITLE
[Hotfix] Add frontend plugin to build frontend automatically

### PR DESCRIPTION
**Pull request by zhoujinsong**
## Why are the changes needed?

When I tried to find the cause of #2660 and #2661, I found that the reason of the issues was that the static files of `ams-dashboard` were not updated.

At present, every time when we make changes to the front-end code, we have to manually build and push the front-end static files, this process is complex and esily introduces unnecessary errors. So I've removed the pre-built front-end files from the repository and added a plugin for automatic building.

## Brief change log

- Remove static files from ams-dashboard.
- Add frontend plugin to build frontend automatically.

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [x] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (no)
- If yes, how is the feature documented? (not applicable)

### CODE REVIEW

**Review by zhangmo8 — APPROVED** [review]
LGTM

**Comment by zhongqishang** [comment]
@zhoujinsong Thanks for your contribution.
Do we not need the `frontend` profile? Would it be better to keep this and change the default value to true?

**Comment by tcodehuber** [comment]
@zhoujinsong Maybe we should update the Markdown in `ams/dashboard/README.md`.
image

**Comment by zhoujinsong** [comment]
> @zhoujinsong Thanks for your contribution. Do we not need the `frontend` profile? Would it be better to keep this and change the default value to true?

It seems necessary to build the frontend now, otherwise the unit tests for AMS will fail, and the packaged AMS won't run properly. Therefore, I don't think there's any need to retain this profile anymore.

**Comment by zhoujinsong** [comment]
> @zhoujinsong Thx for your great job. Maybe we should update the Markdown in `ams/dashboard/README.md`. 

Thanks a lot for the review and suggestion. I have removed the out of date messages.

**Comment by zhoujinsong** [comment]
@zhongqishang @tcodehuber 
I have made some changes according to the review comments, please take another look.

**Review by tcodehuber — APPROVED** [review]
LGTM, thanks for your great job.

**Review by zhongqishang — APPROVED** [review]
LGTM.

**Pull request merged**
