### PR TITLE
[AMORO-2683] Modify the job name of SparkOptimizer and FlinkOptimizer

### LINKED ISSUE #2683: [Improvement]: Modify the default job name of Flink optmizer
### Search before asking

- [X] I have searched in the [issues](https://github.com/NetEase/amoro/issues?q=is%3Aissue) and found no similar issues.

### What would you like to be improved?

The current task name of FlinkOptimizer defaults to `amoro-flink-optimizer` Maybe we should add some more identifiers, such as `amoro-flink-optimizer_{group}_{id}`

### How should we improve?

_No response_

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Subtasks

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by huyuanfeng2018**
## Why are the changes needed?

Close #2683.

## Brief change log

-

## How was this patch tested?

- [ ] Add some test cases that check the changes thoroughly including negative and positive cases if possible

- [ ] Add screenshots for manual tests if appropriate

- [ ] Run test locally before making a pull request

## Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

### CODE REVIEW

**Comment by tcodehuber** [comment]
Thanks for your contribution. Furthermore, can you explain the initial goal how you want add more identifiers for flink/spark's job name? IMHO, we can shorten the job name format, because resourceId is unique, such as ams-optimizer-%s (resourceId).

**Comment by huyuanfeng2018** [comment]
> Thanks for your contribution. Furthermore, can you explain the initial goal how you want add more identifiers for flink/spark's job name? IMHO, we can shorten the job name format, because resourceId is unique, such as ams-optimizer-%s (resourceId).

The initial motivation was because when I submitted the Flink optimizer job in the same Flink session cluster, I found that their job names were all the same, which was not conducive to my differentiation, so I wanted to change the job name. At the same time, I found that the spark optimizer also had a fixed name. So I think it should be modified together (I think if the spark task is submitted to yarn, the job name will also be displayed on the background webui, and adding some identifiers will make it easier to distinguish)


> resourceId is unique, such as ams-optimizer-%s (resourceId)

The resource is indeed unique, but you cannot get the resourceid on the amoro page, so I think it is better to add group

**Comment by tcodehuber** [comment]
The `Optimizers` tab in AMS web console can have more detail infos for every optimizer instance later( touchTime, startTime, token, resourceId etc.)

**Comment by huyuanfeng2018** [comment]
> The `Optimizers` tab in AMS web console can have more detail infos for every optimizer instance later( touchTime, startTime, token, resourceId etc.)

ok,
for naming `ams-optimizer-%s` +1

**Comment by tcodehuber** [comment]
LGTM

**Review by tcodehuber — APPROVED** [review]

**Comment by huyuanfeng2018** [comment]
I'll wait and see if anyone else has any other opinions, Then merge this pr.

**Review by czy006 — APPROVED** [review]
LGTM +1

**Pull request merged**
